### ISSUE TITLE
Change --o to --e

### ISSUE THREAD

**Issue by tkornut** [IBM/mi-prometheus#65]
I have analyzed all workers, in my opinion there is no conflict with --e(xperiments_dir)

This is one of few flags that are shared along all workers and grid workers and outputdir is misleading, as in the case of most of them this is also input dir....

@vmarois what do you think about that?

This issue relates to #25

**Comment by vmarois** [comment]
Agreed! We should make clearer the distinction between:
- The 'input' directory to some workers, like the GridTesters
- The 'experiments' directory, which is where the logs, models, results etc. are saved, which is mostly useful for the trainers (since the testers should find the directory path from the indicated model with `--m`)
