### ISSUE TITLE
Add option to remove keys from registry

### ISSUE THREAD

**Issue by tkornut** [IBM/mi-prometheus#99]
TL;DR:
We need an option to remove keys from registry, so they won't be present in the exported config file ;)

What we are facing is a problem with *reproducible testing*.

- @vmarois is working on "multi-testing", that requires to add list of params [problem names etc.] into "testing" config section (PR #98 )
 - as a result, the "testing" section of the test configuration or all tests performed by our "multi-tester" will contain the same list, so running tester for one of the saved test configuration will result in running multiple tests, instead of reproducing the one.

**Comment by aasseman** [comment]
That's how I think it could be implemented properly:
- Add `del_default_params` and `del_config_params` both in `ParamInterface` and `ParamRegistry`
- In `ParamRegistry`, where the deletion will be actually implemented, we would need the equivalent of `update_dict_recursively([...])` but for deleting, but it will be much simpler, since there will be no recursion needed. Indeed, if you remove the root of any subtree, then all of its subtrees/leaves will be removed.
- (optional, if feasible) implement `__del__` for `ParamInterface`, such that you can directly do `del params[key]` to remove the entire subtree under *key*. The only issue here though is that it will be unclear (when reading the code) if it will delete the default or the config params, or both.
  - Note that this might be hard to achieve, because sometimes when doing `params[key]`, you get a value (leaf of the tree), instead of a new ParamInterface, and I don't if it is possible to call `ParamInterface`'s implementation of `__del__` in that case.
